# Generated by Django 2.1.5 on 2019-01-30 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotebook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='background',
            field=models.ImageField(upload_to='backgrounds/'),
        ),
    ]
